[project]
name = "cml-schemas"
version = "2.1.0"
description = "CML Spark schemas"
readme = "README.md"
requires-python = ">=3.10, <4"
license = { text = "MIT" }
authors = [
  { name = "NHS England Data Science team", email = "datascience@nhs.net" }
]
dependencies = [
  "pyspark>=3.5",
  "pandas>=1.5",
]

[project.urls]
Repository = "https://github.com/nhsengland/cml-schemas"

[project.optional-dependencies]
dev = [
  "pytest>=9.0.2,<10.0.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=65.0"]
build-backend = "setuptools.build_meta"

